// Use mimalloc globally for 15-40% allocation speedup on malloc-heavy workloads.
#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

pub mod protocol {
    include!(concat!(env!("OUT_DIR"), "/netconduit.rs"));
}

pub mod core;
pub mod security;

#[cfg(feature = "python")]
pub mod python;

// ── Flutter Rust Bridge v2 ──────────────────────────────────────────────────
// `frb_generated` is produced by `flutter_rust_bridge_codegen generate`.
// It must live at the crate root so the StreamSink type alias is accessible as
// `crate::frb_generated::StreamSink` from api/mod.rs.
#[cfg(feature = "flutter")]
#[allow(clippy::all, dead_code, unused)]
pub mod frb_generated; // <- generated by codegen; committed to the repo

#[cfg(feature = "flutter")]
pub mod api;

// Re-export the flutter_rust_bridge macro for downstream consumers.
#[cfg(feature = "flutter")]
pub use flutter_rust_bridge::frb;
