// ─────────────────────────────────────────────────────────────────────────────
// NetConduit — Flutter Rust Bridge v2  API  (user-facing Rust surface)
//
// StreamSink is imported from `crate::frb_generated` — generated by running:
//   flutter_rust_bridge_codegen generate
// from the repo root.  The codegen creates:
//   • netconduit_core/src/frb_generated.rs   (Rust glue)
//   • flutter/netconduit/lib/src/frb_generated.dart  (Dart glue)
// ─────────────────────────────────────────────────────────────────────────────

use std::sync::{Arc, Mutex};
// StreamSink is generated by codegen; this is the canonical FRB v2 import.
use crate::frb_generated::StreamSink;

use crate::core::{
    ConduitClient, ConduitServer, ConduitEvent,
    compute_checksum, verify_checksum,
    compress_bytes, decompress_bytes,
    stun_punch_hole as core_stun_punch_hole,
    ChannelConfig, ChannelMode, CompressionPolicy,
    metrics_snapshot,
    write_framed_stream,
    make_message_frame,
    METRICS,
};
use std::sync::atomic::Ordering;

// ─── Event types ─────────────────────────────────────────────────────────────

/// All events pushed from Rust → Dart via StreamSink.
/// FRB generates a sealed class hierarchy on the Dart side.
pub enum NetConduitEvent {
    /// A remote peer connected.  `client_id` = socket addr string.
    Connected { client_id: String },
    /// A raw byte message arrived.
    Message { client_id: String, payload: Vec<u8> },
    /// A named binary stream arrived (already decompressed).
    BinaryStream { client_id: String, name: String, payload: Vec<u8> },
    /// A full-duplex stream was opened. The handle is not FRB-exposed yet
    /// (requires `make codegen`); use the Rust API directly in the meantime.
    DuplexStreamOpen { client_id: String, channel_name: String },
    /// A remote peer disconnected.
    Disconnected { client_id: String },
}

/// Stats snapshot — returned from `NetConduitServerHandle::stats()`.
pub struct NetConduitStats {
    pub connected_clients: Vec<String>,
    pub connection_count: u32,
    /// Process-wide bytes sent across all connections.
    pub bytes_sent: u64,
    /// Process-wide bytes received across all connections.
    pub bytes_received: u64,
    /// Process-wide messages sent.
    pub messages_sent: u64,
    /// Process-wide messages received.
    pub messages_received: u64,
}

// ─── Opaque handles ───────────────────────────────────────────────────────────

/// Opaque server handle — Dart holds this via `RustOpaque`.
pub struct NetConduitServerHandle {
    pub(crate) inner: ConduitServer,
}

impl NetConduitServerHandle {
    pub fn stop(&self) {
        self.inner.stop();
    }

    pub fn send_message(&self, client_id: String, payload: Vec<u8>) {
        self.inner.send_message(client_id, payload);
    }

    pub async fn send_binary_stream(
        &self,
        client_id: String,
        stream_name: String,
        data: Vec<u8>,
    ) -> anyhow::Result<()> {
        self.inner.send_binary_stream(&client_id, &stream_name, data).await
    }

    /// Broadcast to all peers concurrently. Uses Arc internally — no N-copies.
    pub fn broadcast(&self, payload: Vec<u8>) {
        self.inner.broadcast(payload);
    }

    pub fn stats(&self) -> NetConduitStats {
        let clients = self.inner.connected_clients();
        let count = clients.len() as u32;
        let (bs, br, ms, mr, _, _, _) = metrics_snapshot();
        NetConduitStats {
            connected_clients: clients,
            connection_count: count,
            bytes_sent: bs,
            bytes_received: br,
            messages_sent: ms,
            messages_received: mr,
        }
    }

    pub fn is_connected(&self, client_id: String) -> bool {
        self.inner.is_connected(&client_id)
    }

    /// Raw DER bytes of this server's TLS certificate.
    /// Share with clients to enable cert pinning instead of DummyVerifier.
    ///
    /// NOTE: not yet FRB-exposed — run `make codegen` to add Dart bindings.
    pub fn certificate_der(&self) -> Vec<u8> {
        self.inner.cert_der.clone()
    }

    /// Register a named logical channel with custom reliability and compression policy.
    ///
    /// Example — register a low-latency unreliable channel for game state updates:
    /// ```rust
    /// handle.register_channel(ChannelConfig::unreliable("game_state"));
    /// ```
    pub fn register_channel(&self, name: String, mode: String, compression: String) {
        let mode = match mode.as_str() {
            "unreliable" => ChannelMode::Unreliable,
            "unordered"  => ChannelMode::ReliableUnordered,
            _            => ChannelMode::ReliableOrdered,
        };
        let policy = match compression.as_str() {
            "never"  => CompressionPolicy::Never,
            "always" => CompressionPolicy::Always,
            _        => CompressionPolicy::Auto,
        };
        self.inner.register_channel(ChannelConfig { name, mode, compression: policy });
    }

    /// Send a raw QUIC datagram to [client_id] (unreliable, ~1200 B max, lowest latency).
    pub fn send_datagram(&self, client_id: String, payload: Vec<u8>) -> anyhow::Result<()> {
        self.inner.send_datagram(&client_id, payload)
    }

    /// Broadcast a raw QUIC datagram to ALL peers.
    pub fn broadcast_datagram(&self, payload: Vec<u8>) {
        for cid in self.inner.connected_clients() {
            let _ = self.inner.send_datagram(&cid, payload.clone());
        }
    }
}

/// Opaque client handle — Dart holds this via `RustOpaque`.
pub struct NetConduitClientHandle {
    pub(crate) inner: Arc<Mutex<Option<ConduitClient>>>,
}

impl NetConduitClientHandle {
    pub async fn disconnect(&self) {
        // Extract tx_stop and conn without holding the mutex across the await.
        let tx_stop = {
            let guard = self.inner.lock().unwrap();
            guard.as_ref().map(|c| c.tx_stop.clone())
        };
        if let Some(tx) = tx_stop {
            let _ = tx.send(()).await;
        }
        self.inner.lock().unwrap().take();
    }

    pub async fn send_message(&self, payload: Vec<u8>) -> anyhow::Result<()> {
        // Extract conn without holding the Mutex across any await point.
        let conn = {
            let guard = self.inner.lock().unwrap();
            match guard.as_ref() {
                Some(c) => c.conn.clone(),
                None => anyhow::bail!("Client is not connected"),
            }
        };
        let frame = make_message_frame(payload).await?;
        let n = frame.len() as u64;
        let mut s = conn.open_uni().await?;
        s.write_all(&frame).await?;
        s.finish()?;
        METRICS.bytes_sent.fetch_add(n, Ordering::Relaxed);
        METRICS.messages_sent.fetch_add(1, Ordering::Relaxed);
        Ok(())
    }

    pub async fn send_binary_stream(
        &self,
        stream_name: String,
        data: Vec<u8>,
    ) -> anyhow::Result<()> {
        let conn = {
            let guard = self.inner.lock().unwrap();
            match guard.as_ref() {
                Some(c) => c.conn.clone(),
                None => anyhow::bail!("Client is not connected"),
            }
        };
        let (mut send, _) = conn.open_bi().await?;
        write_framed_stream(&mut send, &stream_name, data, CompressionPolicy::Auto).await
    }

    /// Send a raw QUIC datagram (unreliable, lowest latency, ~1200 B max).
    pub fn send_datagram_raw(&self, payload: Vec<u8>) -> anyhow::Result<()> {
        let guard = self.inner.lock().unwrap();
        match guard.as_ref() {
            Some(c) => c.send_datagram(&payload),
            None => anyhow::bail!("Client is not connected"),
        }
    }

}

// ─── Top-level lifecycle functions ───────────────────────────────────────────

/// Start a server and push events to [sink].
pub async fn nc_start_server_streaming(
    host: String,
    port: u16,
    sink: StreamSink<NetConduitEvent>,
) -> anyhow::Result<NetConduitServerHandle> {
    use tokio::sync::mpsc;

    let (tx, mut rx) = mpsc::channel::<ConduitEvent>(8192);
    let server = ConduitServer::start(&host, port, tx, 0).await?;

    tokio::spawn(async move {
        while let Some(ev) = rx.recv().await {
            if sink.add(map_event(ev)).is_err() { break; }
        }
    });

    Ok(NetConduitServerHandle { inner: server })
}

/// Connect a client and push events to [sink].
pub async fn nc_connect(
    host: String,
    port: u16,
    connect_timeout_secs: u64,
    local_port: u16,
    sink: StreamSink<NetConduitEvent>,
) -> anyhow::Result<NetConduitClientHandle> {
    use tokio::sync::mpsc;

    let timeout = if connect_timeout_secs == 0 { 10 } else { connect_timeout_secs };
    let lport = if local_port == 0 { None } else { Some(local_port) };

    let (tx, mut rx) = mpsc::channel::<ConduitEvent>(8192);
    let client = ConduitClient::connect(&host, port, timeout, tx, lport).await?;

    tokio::spawn(async move {
        while let Some(ev) = rx.recv().await {
            if sink.add(map_event(ev)).is_err() { break; }
        }
    });

    Ok(NetConduitClientHandle {
        inner: Arc::new(Mutex::new(Some(client))),
    })
}

// ─── Utility functions ────────────────────────────────────────────────────────

pub fn nc_checksum(data: Vec<u8>) -> String {
    compute_checksum(&data)
}

pub fn nc_verify_checksum(data: Vec<u8>, expected: String) -> bool {
    verify_checksum(&data, &expected)
}

pub fn nc_compress_raw(data: Vec<u8>) -> anyhow::Result<Vec<u8>> {
    compress_bytes(&data)
}

pub fn nc_decompress_raw(data: Vec<u8>) -> anyhow::Result<Vec<u8>> {
    decompress_bytes(&data)
}

pub fn nc_stun_punch_hole_raw(
    stun_server: String,
    local_port: u16,
    peer_addr: String,
) -> anyhow::Result<String> {
    core_stun_punch_hole(stun_server, local_port, peer_addr)
}

// ─── Private helpers ──────────────────────────────────────────────────────────

fn map_event(ev: ConduitEvent) -> NetConduitEvent {
    match ev {
        ConduitEvent::Connect      { client_id }                          => NetConduitEvent::Connected  { client_id },
        ConduitEvent::Message      { client_id, payload }                 => NetConduitEvent::Message    { client_id, payload },
        ConduitEvent::BinaryStream { client_id, name, payload }           => NetConduitEvent::BinaryStream { client_id, name, payload },
        ConduitEvent::DuplexStreamOpen { client_id, stream }              => NetConduitEvent::DuplexStreamOpen {
            client_id,
            channel_name: stream.name,
            // The actual DuplexStream handle is not FRB-serializable without codegen.
            // Callers using the Rust API receive the full ConduitEvent directly.
        },
        ConduitEvent::Disconnect   { client_id }                          => NetConduitEvent::Disconnected { client_id },
    }
}
